Add Sniff to require the usage of ::class whenever possible
leroy-merlin-br/php-coding-standard pull request #11
Opened 2018-11-09 22:39 UTC by carusogabriel

Resolves #9.

This Sniff also improves the performance: https://belineperspectives.com/2017/03/13/get_classthis-vs-staticclass/ :tada:

2018-11-12 12:39 UTC, ravanscafi approved these changes

2018-11-12 12:48 UTC, gmsantos approved these changes

2018-11-12 13:21 UTC, brnbp approved these changes

2018-11-12 15:58 UTC, ejosess approved these changes

2018-11-19 12:27 UTC, vitorbari approved these changes

2019-01-03 18:22 UTC, ravanscafi requested changes
Please add tests :)

2019-01-08 12:05 UTC, gemidio approved these changes

2019-01-08 13:23 UTC, ThiagoNP approved these changes

2019-01-08 15:26 UTC, alemferreira approved these changes

2019-01-09 14:04 UTC, ravanscafi approved these changes

2019-01-09 15:40 UTC, merged