Forbid empty comments through the code
leroy-merlin-br/php-coding-standard pull request #20
Opened 2019-01-12 18:37 UTC by carusogabriel

2019-01-14 11:43 UTC, gmsantos approved these changes

2019-01-15 11:39 UTC, ravanscafi approved these changes

2019-01-31 17:31 UTC, diegofelix requested changes
tem alguns comentários que vão pular linha.
```php
// here you may add some config
// through the files you are workin
//
// the same could be applied to config files.
```

Por isso, meu voto é não.

2019-01-31 18:52 UTC, gmsantos commented
@diegofelix if should be a multiline comment then:

/* 
 * here you may add some config
 * through the files you are workin
 *
 * the same could be applied to config files.
 */

2019-05-23 18:47 UTC, closed without merging