Add rules for spaces between traits and forbidden same line declaration
leroy-merlin-br/php-coding-standard pull request #21
Opened 2019-01-12 18:57 UTC by carusogabriel

2019-01-14 11:44 UTC, gmsantos approved these changes

2019-01-15 11:40 UTC, ravanscafi approved these changes

2019-01-31 17:29 UTC, diegofelix requested changes

2019-01-31 17:29 UTC, diegofelix commented on tests/expected/example-class.php
> +    use Trait1;
Não vejo motivo pra forçar pular linha, por isso, meu voto é não.

2019-05-23 18:47 UTC, closed without merging